pogo/pdb_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "pdb_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('item/<int:item_id>', views.item, name='item')
]

pogo/programming_database/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from programming_database import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pdb_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pogo/pdb_app/models.py
from django.db import models

class Category(models.Model):
    class Meta:
        verbose_name_plural = 'categories'

    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

pogo/pdb_app/views.py
from django.http import HttpResponse
from django.template import loader

from .models import Item, Category

def index(request):
    # Category.objects.get(id=1).item_set.all)()
    template = loader.get_template('pdb_app/index.html')
    context = {
        'categories': Category.objects.all()
    }
    return HttpResponse(template.render(context, request))

def item(request, item_id):
    try:
        itm = Item.objects.get(id=item_id)
    except Item.DoesNotExist:
        itm = None
    
    template = loader.get_template('pdb_app/item.html')
    context = {
        'item': itm
    }
    return HttpResponse(template.render(context, request))

pogo/pdb_app/templates/pdb_app/base.html
{% load static %}

<!doctype html>

<html>
    <head>
        <link rel="stylesheet" href="{% static 'pdb_app/style.css' %}">

        {% block head %}
        {% endblock %}
    </head>
    <body>
        <h1>Programming Database</h1>
        <hr>
        <br>
        {% block body %}
        {% endblock %}
    </body>
</html>

pogo/pdb_app/templates/pdb_app/index.html
{% extends 'pdb_app/base.html' %}

{% block head %}
    <title>Home - Programming Database</title>
{% endblock %}

{% block body %}

    {% for category in categories %}
        <h2>{{ category.name }}</h2>
        {% for item in category.item_set.all %}
            <a href="{% url 'pdb_app:item' item.id %}">{{ item.name }}</a>
        {% endfor %}
        <br>
    {% endfor %}

    {% comment %} {% for item in items %}
        <a href="{% url 'pdb_app:item' item.id %}">{{ item.name }}</a>
    {% endfor %} {% endcomment %}

{% endblock %}

pogo/pdb_app/templates/pdb_app/item.html
{% extends 'pdb_app/base.html' %}

{% block head %}
    {% if item != None %}
        <title>{{ item.name }} - Programming Database</title>
    {% else %}
        <title> Invalid Item - Programming Database</title>
    {% endif %}
{% endblock %}

{% block body %}
    <a href="{% url 'pdb_app:index' %}">&lt; Back</a>

    {% if item != None %}
        <h2>{{ item.name }}</h2>
        <h4>{{ item.category.name }}</h4>
        <p>{{ item.description }}</p>

        {% if item.image != None %}
            <img src="{{ item.image.url }}">
        {% endif %}
    {% else %}
        <p>Invalid Item ID.</p>
    {% endif %}
{% endblock %}